export const SCREEN_SPLASH = 'SCREEN_SPLASH';
export const SCREEN_AUTH_PHONE = 'SCREEN_AUTH_PHONE';
export const SCREEN_AUTH_CODE = 'SCREEN_AUTH_CODE';
export const SCREEN_REGISTER = 'SCREEN_REGISTER';
export const SCREEN_SEARCH = 'SCREEN_SEARCH';
export const SCREEN_MESSAGES = 'SCREEN_MESSAGES';
export const SCREEN_PROFILE = 'SCREEN_PROFILE';
export const SCREEN_HOME = 'SCREEN_HOME';
export const SCREEN_TOURNAMENTS = 'SCREEN_TOURNAMENTS';

export const SCREEN_CREATE_CHOOSE_TYPE = 'SCREEN_CREATE_CHOOSE_TYPE';
export const SCREEN_CREATE_TOURNAMENT = 'SCREEN_CREATE_TOURNAMENT';
export const SCREEN_CREATE_TOURNAMENT_CHOOSE_CLUB =
  'SCREEN_CREATE_TOURNAMENT_CHOOSE_CLUB';
export const SCREEN_CREATE_TOURNAMENT_INFORMATION_1 =
  'SCREEN_CREATE_TOURNAMENT_INFORMATION_1';
export const SCREEN_CREATE_TOURNAMENT_INFORMATION_2 =
  'SCREEN_CREATE_TOURNAMENT_INFORMATION_2';
